import yaml


# Load yaml
with open('./nhsl.yml', 'r', encoding='utf-8') as f:
    nhsl_yml = yaml.load(f, Loader = yaml.Loader)

# Endlines staying as \n without replacement
description = nhsl_yml['description']['en'].replace('\\n', '\n')
description_fr = nhsl_yml['description']['fr'].replace('\\n', '\n')

# Generate links to available datasets
datasets = ''
datasets_fr = ''
for layer in nhsl_yml['layers']:
    set = [x for x in nhsl_yml['datasets'] if x['id'] == layer][0]
    datasets += f'- [{set["title"]["en"]}](https://github.com/OpenDRR/national-human-settlement/tree/main/{set["folder"]})' + '\n'
    datasets_fr += f'- [{set["title"]["fr"]}](https://github.com/OpenDRR/national-human-settlement/tree/main/{set["folder"]})' + '\n'

# English readme text
readme = f'''Autogenerated from nhsl.yml
[En français](https://github.com/OpenDRR/national-human-settlement/blob/main/LISEZMOI.md)

# National Human Settlement Layer

## Overview of this Repository

This repository is used for the development of the National National Human Settlement Layer (NHSL). {description}

### Available Datasets

{datasets}
## Technical Use

{nhsl_yml['technical']['en']}
## Documentation

{nhsl_yml['documentation']['en']}
## A Note on Acceptable Use

{nhsl_yml['acceptable']['en']}
## Attribution

{nhsl_yml['attribution']['en']}'''

# French readme text
lisezmoi = f'''Autogenerated from nhsl.yml
[In English](https://github.com/OpenDRR/national-human-settlement/blob/main/README.md)

Traduit avec www.DeepL.com/Translator (version gratuite)

# La couche des zones de peuplement au niveau national

## Vue d'ensemble de ce référentiel

Ce dépôt est utilisé pour le développement de la couche des zones de peuplement au niveau national (couche ZPN). {description_fr}

### Ensembles de données disponibles

{datasets_fr}
### Utilisation technique

{nhsl_yml['technical']['fr']}
## Documentation

{nhsl_yml['documentation']['fr']}
## Une note sur l'utilisation acceptable

{nhsl_yml['acceptable']['fr']}
## Attribution

{nhsl_yml['attribution']['fr']}'''

# Write to files
with open('README.md', 'w', encoding='utf-8') as f:
    f.write(readme)

with open('LISEZMOI.md', 'w', encoding='utf-8') as f:
    f.write(lisezmoi)


# Generate readme's for each active layer
for layer in nhsl_yml['layers']:
    set = [x for x in nhsl_yml['datasets'] if x['id'] == layer][0]
    description = set['description']['en'].replace('\\n', '\n')
    description_fr = set['description']['fr'].replace('\\n', '\n')

    # Write english
    with open(f'./{set["folder"]}/README.md', 'w', encoding='utf-8') as f:
        f.write(f'''Autogenerated from nhsl.yml

[En français](https://github.com/OpenDRR/national-human-settlement/blob/main/physical-exposure/LISEZMOI.md)

# National Human Settlement - {set["title"]["en"]}
 
{description}''')

    # Write french
    with open(f'./{set["folder"]}/LISEZMOI.md', 'w', encoding='utf-8') as f:
        f.write(f'''Autogenerated from nhsl.yml

[In English](https://github.com/OpenDRR/national-human-settlement/blob/main/physical-exposure/README.md)

# Zones de peuplement au niveau national - {set["title"]["fr"]}
 
{description_fr}''')
