name: Check for dead links on GitHub Pages

on:
  pull_request:
    types: [ opened, synchronize, edited, reopened ]

jobs:
  broken-link-checker:
    name: Check for broken links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./docs/_site

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --exclude '^https://www\.canada\.ca/' --fallback-extensions html 'docs/_site/**/*.html'
          fail: false

      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code >= 2
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
